name: ArXiv通知テスト用

on:
  workflow_dispatch:  # 手動実行トリガー

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Run script
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: python main_debug_teams.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: arxiv-csv
          path: arxiv_generative_ai.csv
